# -*- coding: utf-8 -*-
"""Módulo if - Aula 02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qne7zahWlGXBKGlojcKRRdHhgXwpUk73

# Blocos e Identação

## Estrutura
Sempre que usamos o if ou qualquer outra estrutura no Python, devemos usar a identação para dizer para o Programa onde a estrutura começa e onde ela termina.

Isso vai ajudar muito quando tivermos mais de 1 condição ao mesmo tempo e quando tivermos várias ações para fazer dentro de um if.

### Várias ações em 1 if:

if condicao:
    alguma coisa
    outra coisa
    outra coisa mais
    outra coisa ainda mais
else:
    uma coisa
    uma coisa mais
    coisa final

## Exemplo
Vamos fazer um novo exemplo abaixo:

Digamos que você precisa criar um programa para um fundo de investimentos conseguir avaliar o resultado de uma carteira de ações e o quanto de taxa deverá ser pago.

A regra desse fundo de investimentos é:

- O fundo se compromete a entregar no mínimo 5% de retorno ao ano.
- Caso o fundo não consiga entregar os 5% de retorno, ele não pode cobrar taxa dos seus investidores.
- Caso o fundo consiga entregar mais de 5% de retorno, ele irá cobrar 2% de taxa dos seus investidores.
- Caso o fundo consiga mais de 20% de retorno, ele irá cobrar 4% de taxa dos seus investidores.
"""



"""### Mais de uma condição ao mesmo tempo:

if condicao_1:
    o que fazer se a condição 1 for verdadeira
    if condicao_2:
        o que fazer se a condição 1 e 2 for verdadeira
    else:
        o que fazer se a condição 2 for falsa (mas a condição 1 é verdadeira)
else:
    o que fazer se a condição 1 for falsa

## Cuidado importante: repetição de código

Sempre que possível, evite repetir código. De forma geral:<br>
"Se você está repetindo um código, existe uma forma melhor de fazer"
"""