# -*- coding: utf-8 -*-
"""Indice e Tamanho de String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ePABE0vnQ_FnPtpfBJlJq6iPX52mynek

0 1 2 3 4 5 6 7 8 9 10 11 12 13
l i r a @ g m a i l  .  c  o m

Pegar um item de uma string: texto[índice]
Pegar o tamanho de um texto: len(texto)
"""

email = 'lira@gmail.com'
nome = 'João Lira'